site_name: 中文 Markdown 文章
copyright: >
  Copyright &copy; 2023
  <a href="https://seiri-blog.github.io">seiri's blog</a>
site_description: >
  2019年~2021年所记录的，中文Markdown的文章，详细请参照文章列表
site_author: seiri
nav:
  - 文章列表: index.md
  - 我的博客（日文）: https://seiri-blog.github.io
extra:
  homepage: https://seiri-blog.github.io/article-zh/
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ryuseiri
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/people/Ryu-Seiri/100087864783411
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Seiriryu
    - icon: fontawesome/brands/quora
      link: https://qiita.com/Seiri
    - icon: fontawesome/brands/blogger
      link: https://knowstechnic.blogspot.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCph3vDUIHt68iR0vtHbChaw
    - icon: fontawesome/brands/bootstrap
      link: https://space.bilibili.com/140506788
theme:
  name: material
  custom_dir: overrides
  logo: https://seiri-blog.github.io/favicon.ico
  favicon: https://seiri-blog.github.io/favicon.ico
  language: zh

  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.annotate
  plugins:
    - meta
    - blog
    - search
    - tags
    - rss

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - assets/stylesheets/extra.css
